In [13]:
from tensorflow.keras.preprocessing.text import one_hot

In [1]:
sent=[
    "the glass of milk",
    "the glass of juice",
    "the cup of tea",
    "I am a good boy",
    "I am a good developer",
    "understand the meaning of words",
    "your videos are good",
]

In [15]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

## Define the vocabulary size


In [16]:
voc_size=10000

## One Hot Representation

In [17]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5796, 929, 7096, 716],
 [5796, 929, 7096, 783],
 [5796, 1620, 7096, 295],
 [5413, 5703, 3398, 6704, 1769],
 [5413, 5703, 3398, 6704, 3983],
 [8099, 5796, 1321, 7096, 8910],
 [8092, 5036, 612, 6704]]

In [18]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

### Word Emebedding Representation

In [20]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [22]:
import numpy as np

In [25]:
sent_length=8
Embedding_docs=pad_sequences(one_hot_repr,padding="pre",maxlen=sent_length)
print(Embedding_docs)

[[   0    0    0    0 5796  929 7096  716]
 [   0    0    0    0 5796  929 7096  783]
 [   0    0    0    0 5796 1620 7096  295]
 [   0    0    0 5413 5703 3398 6704 1769]
 [   0    0    0 5413 5703 3398 6704 3983]
 [   0    0    0 8099 5796 1321 7096 8910]
 [   0    0    0    0 8092 5036  612 6704]]


### Feature Representation

In [27]:
dim=10

In [29]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile("adam","mse")

In [30]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [31]:
model.predict(Embedding_docs)

1/1 [==============================] - 0s 224ms/step


array([[[ 4.20486219e-02, -4.97347377e-02, -1.62640437e-02,
          3.91686074e-02,  4.71829809e-02, -1.43494233e-02,
          1.89153887e-02, -1.28277391e-03,  1.10001452e-02,
         -1.79464817e-02],
        [ 4.20486219e-02, -4.97347377e-02, -1.62640437e-02,
          3.91686074e-02,  4.71829809e-02, -1.43494233e-02,
          1.89153887e-02, -1.28277391e-03,  1.10001452e-02,
         -1.79464817e-02],
        [ 4.20486219e-02, -4.97347377e-02, -1.62640437e-02,
          3.91686074e-02,  4.71829809e-02, -1.43494233e-02,
          1.89153887e-02, -1.28277391e-03,  1.10001452e-02,
         -1.79464817e-02],
        [ 4.20486219e-02, -4.97347377e-02, -1.62640437e-02,
          3.91686074e-02,  4.71829809e-02, -1.43494233e-02,
          1.89153887e-02, -1.28277391e-03,  1.10001452e-02,
         -1.79464817e-02],
        [ 2.21712701e-02,  2.98717879e-02,  1.99900381e-02,
          2.47328170e-02,  4.36853059e-02,  3.66738774e-02,
          6.05630875e-03,  2.46222280e-02,  3.562405

In [32]:
Embedding_docs[0]

array([   0,    0,    0,    0, 5796,  929, 7096,  716])

In [33]:
model.predict(Embedding_docs[0])

1/1 [==============================] - 0s 61ms/step


array([[ 0.04204862, -0.04973474, -0.01626404,  0.03916861,  0.04718298,
        -0.01434942,  0.01891539, -0.00128277,  0.01100015, -0.01794648],
       [ 0.04204862, -0.04973474, -0.01626404,  0.03916861,  0.04718298,
        -0.01434942,  0.01891539, -0.00128277,  0.01100015, -0.01794648],
       [ 0.04204862, -0.04973474, -0.01626404,  0.03916861,  0.04718298,
        -0.01434942,  0.01891539, -0.00128277,  0.01100015, -0.01794648],
       [ 0.04204862, -0.04973474, -0.01626404,  0.03916861,  0.04718298,
        -0.01434942,  0.01891539, -0.00128277,  0.01100015, -0.01794648],
       [ 0.02217127,  0.02987179,  0.01999004,  0.02473282,  0.04368531,
         0.03667388,  0.00605631,  0.02462223,  0.03562405,  0.02702299],
       [ 0.01738383, -0.0008192 ,  0.04928294, -0.03819997, -0.00098645,
        -0.02494891,  0.01403887, -0.03756472, -0.02751687, -0.01674398],
       [ 0.04156185, -0.02207303, -0.04688727,  0.02391017,  0.02354443,
        -0.0066539 , -0.03390083, -0.02391174